services:
  - type: web
    name: squeeze-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python scanner.py
    envVars:
      - key: TICKERS
        value: TSLA,AMC,GME,IONQ,RCAT,SMR
      - key: ALPHA_VANTAGE_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
